# Generated by Django 6.0.3 on 2026-04-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='estate',
            new_name='state',
        ),
    ]
